services:

  telegram-bot:
    image: telegram-bot
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080

  frontend:
    image: nextjs-frontend
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  notification_handler:
    image: notification_handler
    build:
      context: ./notification_handler
      dockerfile: Dockerfile
    depends_on:
      - database
      - frontend

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - 3306:3306