services:

  telegram-bot:
    image: telegram-bot
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    env_file:
      - .env

  frontend:
    image: nextjs-frontend
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000